name: EdgeWorker

on:
  workflow_dispatch:
    inputs:
      testCodeBranch:
        description: 'Test Code Branch'
        required: true
        default: 'stage'
        type: string
      edgeworker:
        description: 'Edge Worker'
        type: choice
        required: true
        default: 'Acrobat_DC_web_stg'
        options:
            - 'Acrobat_DC_web_stg'          
            - 'Acrobat_DC_web_prod'        
      network:
        description: 'Network'
        type: choice
        required: true
        default: 'staging'
        options:
          - 'staging'          
          - 'production'

jobs:
  deploy-edgeworker:     
    name: Deploy EdgeWorker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.testCodeBranch }}

      - name: Build Edge Worker Scripts
        run: |
          npm run ewbuild
          npm run ewprod2stg 
     
      - name: Deploy Edge Worker
        uses: jdmevo123/akamai-edgeworker-action@1.1
        env:
          EDGERC: ${{ secrets.AKAMAI_EDGERC }}
          WORKER_DIR: edgeworkers/${{ inputs.edgeworker }}
        with:
          edgeworkersName: ${{ inputs.edgeworker }}
          network: ${{ inputs.network }}
          groupid: '58544'
