on:
  push:
    branches:
      - stage

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          pr_title: "Ready for Main: ${{ github.ref_name }} into main. ${{ github.base_ref }}"
          pr_body: "Merge to main, commit: ${{ github.sha }} --  ${{ github.head_ref }}"
          pr_reviewer: "@adobecom/creative-cloud-sot,@adobecom/document-cloud-sot,@adobecom/bacom-sot,@adobecom/homepage-sot,@adobecom/miq-sot"
          pr_label: "Ready for Main"
