on:
  push:
    branches:
      - stage

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: "Merge to main"
          pr_assignee: "blainegunn"
          pr_label: "ready-for-main"
