name: Resource Published

# Franklin Sidekick will trigger this workflow when a resource is published
on: 
  repository_dispatch:
    types:
      - resource-published

jobs:
  post-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Show Event Payload
      run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"

    - name: Checkout
      if: ${{ endsWith(github.event.client_payload.path, '.md') }}
      uses: actions/checkout@v3

    - name: Cache dependencies
      if: ${{ endsWith(github.event.client_payload.path, '.md') }}
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}-${{ runner.os }}

    - name: Install dependencies
      if: ${{ endsWith(github.event.client_payload.path, '.md') }} && steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts

    - name: Install playwright browsers
      if: ${{ endsWith(github.event.client_payload.path, '.md') }} && steps.cache.outputs.cache-hit != 'true'
      run: npx playwright install 

    - name: Run Lighthouse Test
      if: ${{ endsWith(github.event.client_payload.path, '.md') }}
      run: node tools/lighthouse/lighthouse.js ${{ github.event.client_payload.path }}

    - name: Update Metadata
      if: ${{ endsWith(github.event.client_payload.path, '.md') }}
      run: node .github/scripts/update_metadata.js
      env:
        UPDATE_METADATA_WEBHOOK: ${{ secrets.UPDATE_METADATA_WEBHOOK }}         
